server:
  port: 8090


# Logging
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    org:
      mdh:
        pmm: WARN
  file:
    name: logs/pmmref/spring-boot-client-logs.log


# Spring Config

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: none


